config/routes.rb
Rails.application.routes.draw do

  get 'attendee/create'

  get 'attendee/delete'

  get '/companies/:id/attendees', to: 'companies#attendees'

  resources :companies
  get 'index/home'

  resources :comments
  resources :meetings
  resources :settings
  resources :users
  resources :goals
  resources :agenda_items
  resources :deliverables

  get '/agenda_items/:id/complete', to: 'agenda_items#complete'

  get '/meetings/:id/send_goals_and_agenda', to:"meetings#send_goals_and_agenda"

  get '/meetings/:id/send_notes', to:"meetings#send_notes"

  post '/parking_lot_items', to: 'parking_lot_items#create'

  delete '/parking_lot_items/:id', to: 'parking_lot_items#destroy'

  post '/attendees', to:'attendee#create'

  delete '/attendees/:id', to:'attendee#destroy'

  root 'meetings#index'
  
  get '/login', to: 'auth#login', as: 'auth_login_url'
  get '/logout', to: 'auth#logout', as: 'auth_logout_url'
  post '/login', to: 'auth#process_login'

  get '/meetings/:id/text', to: 'meetings#text'

  get '/meetings/:id/md', to: 'meetings#markdown'

  get '/meetings/:id/attendees', to: 'meetings#get_meeting_attendees'
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/agenda_item.rb
class AgendaItem < ApplicationRecord
  before_create :set_order
  belongs_to :meeting
  belongs_to :attendee

private
  def set_order
    max_order = AgendaItem.maximum(:order)
    
    self.order = 1
    
    if max_order
        self.order = max_order+1
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :meeting
  has_many :deliverables
  has_many :agenda_items
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :meeting
  belongs_to :user
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :meetings
    has_many :users
end

app/models/deliverable.rb
class Deliverable < ApplicationRecord
    belongs_to :attendee, :class_name => "Attendee"
    belongs_to :meeting
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :meeting
end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :meeting
  belongs_to :user
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  has_many :goals, :class_name => "Goal"
  has_many :agenda_items, :class_name => "AgendaItem"
  has_many :deliverables, :class_name => "Deliverable"
  has_many :parking_lot_items, :class_name => "ParkingLotItem"
  has_many :attendees, :class_name => "Attendee"


 def markdown_to_html(args)

      markdown_raw = ApplicationController.new.render_to_string('meetings/text', layout: false,locals: { meeting: self, goals_and_agendas_only: args[:goals_and_agendas_only]  })

      renderer = Redcarpet::Render::HTML.new(no_links: true, hard_wrap: true)

      markdown = Redcarpet::Markdown.new(renderer, extensions = {strikethrough: true})

      return markdown.render(markdown_raw)
  end
end

app/models/parking_lot_item.rb
class ParkingLotItem < ApplicationRecord
  belongs_to :meeting

end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    def full_name
        return self.first_name+" "+self.last_name
    end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def login
  end
  
  def process_login
    @user = User.find_by(email: params[:email]).try(:authenticate, params[:password])
    if(@user)
      session[:current_user] = @user.id
      session[:company_id] = @user.company_id
      redirect_to params[:redirect_to] || "/"
    else
     flash[:notice] = "There was a problem logging in. Please check your username and password and try again"
     redirect_to "/login?redirect_to="+params[:redirect_to]
    end
    
  end

  def logout
          session[:current_user] = nil
          session[:company_id] = nil
          redirect_to "/"
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy, :text, :markdown, :get_meeting_attendees, :send_goals_and_agenda, :send_notes]

  # GET /meetings
  # GET /meetings.json
  def index
    
    if params[:q]
        uc_q = params[:q].upcase
        @meetings = Meeting.where("UPPER(description) like (?) OR UPPER(meeting_name) like (?)","%#{uc_q}%","%#{uc_q}%").order(date: :desc)
        render partial: "meetings/meeting_list"
      else
        @meetings = Meeting.order(date: :desc)
        @meeting = Meeting.new
        render template: "meetings/index"
    end
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
     @users = User.all.where(company_id: session[:company_id])
  end

  def text
    text = render_to_string('meetings/text', layout: false, locals: {meeting: @meeting, goals_and_agendas_only: false})
    render plain: text, content_type: 'text/plain'
  end

  def markdown

    @markdown_rendered = @meeting.markdown_to_html(goals_and_agendas_only: false)

    render 'markdown', layout: false
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new
  end

  # GET /meetings/1/edit
  def edit
  end

  def send_goals_and_agenda
     AttendeeMailer.goals_and_agenda(@meeting,User.find(session[:current_user])).deliver_now
     render json:{ success: 1 }
  end

  def send_notes
     AttendeeMailer.notes(@meeting,User.find(session[:current_user])).deliver_now
     render json:{ success: 1 }
  end
  def get_meeting_attendees
     query = params[:q]
    respond_to do |format|
     format.json { render json: @meeting.attendees.where("email LIKE ?","#{query}%") }
     format.html { render :partial => "shared/meeting_attendees" }
    end
  end

  # POST /meetings
  # POST /meetings.json
  def create

    @meeting = Meeting.new(meeting_params)

    @meeting[:company_id] = User.find(session[:current_user]).company_id;

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find_by(id: params[:id], company_id: session[:company_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:meeting_name, :description, :start_time, :end_time, :organizer, :time_keeper, :note_taker, :actual_end_time, :company_id, :date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendee_helper.rb
module AttendeeHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/meetings/_agenda_tab.html.erb
<br>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  </div>
  <div class="col-xs-12 col-sm-12 col-md-4 col-lg-5">
    <input type="text" id="new-agenda-item" class="form-control" placeholder="New Agenda Item">
  </div>
  <div class="col-xs-12 col-sm-12 col-md-3 col-lg-4">
    <input type="text" name="" id="new-agenda-item-user-email" class="form-control meeting-attendees-typeahead" placeholder="Who will present (Email)?">
  </div>
  <div class="col-xs-12 col-sm-12 col-md-3 col-lg-2">
    <input type="text" id="new-agenda-item-time-limit" class="form-control" placeholder="Time Limit (Mins)">
  </div>
  <div class="col-xs-12 col-sm-12 col-md-2 col-lg-1">
    <span class="input-group-btn">
      
      <button type="button" class="btn btn-primary add-agenda-item-btn" data-meeting-id="<%= @meeting.id %>">Add</button>
      
    </span>
  </div>
  <hr>
</div>
<div id="agenda-item-container">
  <%= render "shared/meeting_agenda_items" %>
</div>

app/views/meetings/_attendee_tab.html.erb
<br>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  </div>
  <div class="col-xs-12 col-sm-12 col-md-10 col-lg-11">
    <input type="text" id="new-attendee-email" class="form-control company-attendees-typeahead" placeholder="Enter Email (Comma Seperated for multiple)">
  </div>
  <div class="col-xs-12 col-sm-12 col-md-2 col-lg-1">
    <span class="input-group-btn">
      
      <button type="button" id="add-attendee-btn" class="btn btn-primary" data-meeting-id="<%= @meeting.id %>">Add</button>
      
    </span>
  </div>
  <hr>
</div>
<div id="attendee-container">
  <%= render "shared/meeting_attendees" %>
</div>

app/views/meetings/_deliverables_tab.html.erb
<br>
<div>
  <div class="row">
    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
      <input type="text" name="" id="new-deliverable-text" class="form-control" value="" placeholder="What is needed">
    </div>
    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
      <input type="text" name="" id="new-deliverable-user-email" class="form-control meeting-attendees-typeahead" placeholder="Who? (Email)">
    </div>
    <div class="col-xs-12 col-sm-12 col-md-3 col-lg-3">
      <input type="text" name="" id="new-deliverable-due-date" class="form-control datepicker" value="" placeholder="When is it needed?">
    </div>
    <div class="col-xs-12 col-sm-12 col-md-3 col-lg-1">
      <button class="btn btn-primary" id="add-deliverable-button">Add</button>
    </div>
    <hr>
  </div>
  <div id="deliverable-list">
     <%= render "shared/meeting_deliverables" %>
  </div>
</div>

app/views/meetings/_form.html.erb
<%= form_for(meeting) do |f| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :meeting_name %>
    <%= f.text_field :meeting_name, class: 'form-control' %>
  </div>
<br>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control'  %>
  </div>
<br>
  <div class="field">
    <label>Due Date</label>
   <input type="text" class="form-control datepicker" name="meeting[date]">
  </div>

<br><br>
  <div class="actions pull-right">
    <%= f.submit 'submit', class: ["btn","btn-success"], value: 'Add Meeting' %>
  </div>
<% end %>

app/views/meetings/_goal_tab.html.erb
<br>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
  </div>
  <div class="col-xs-12 col-sm-12 col-md-10 col-lg-11">
    <input type="text" id="new_goal" class="form-control" placeholder="New Goal">
  </div>
  <div class="col-xs-12 col-sm-12 col-md-2 col-lg-1">
    <span class="input-group-btn">
      
      <button type="button" class="btn btn-primary add-goal-btn" data-meeting-id="<%= @meeting.id %>">Add</button>
      
    </span>
  </div>
  <hr>
</div>
<div id="goal-container">
  <%= render "shared/meeting_goals" %>
</div>

app/views/meetings/_meeting_list.html.erb
<div class="row">
    <% @meetings.each do |meeting| %>
    <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4">
        <div class="panel panel-default meeting-panel">
            <div class="panel-heading">
                <a href="/meetings/<%= meeting.id %>"><h3 class="panel-title"><%= meeting.meeting_name %> <%= meeting.date %></h3></a>
            </div>
            <div class="panel-body">
                <p><%= meeting.description %></p>
            </div>
        </div>
    </div>
    <% end %>
</div>

app/views/meetings/_parking_tab.html.erb
<br>
<div class="row">
  <div class="col-xs-12 col-sm-12 col-md-11 col-lg-11">
    <input type="text" class="form-control" id="new-parking-lot-item" placeholder="Start typing here to park something">
  </div>
  <div class="col-xs-12 col-sm-12 col-md-1 col-lg-1">
    <button class="btn btn-primary" id="add-parking-lot-button" data-meeting-id="<%= @meeting.id %>">Add</button>
  </div>
  <hr>
</div>


<div id="parking-lot-list">
  <%= render "shared/meeting_parking_lot_items" %>
</div>

app/views/meetings/_timeup_modal.html.erb
<div class="modal fade" id="time-is-up-modal">
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title">Time Is Up!</h4>
    </div>
    <div class="modal-body">
      <p>The time allotted for this agenda item has passed, please click continue and move on to the next one.</p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default end-timer" data-dismiss="modal">Continue</button>
    </div>
  </div>
</div>
</div>

app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<div class="row">
    <div class="col-xs-12 col-sm-12 col-md3 col-lg-3">
        
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Search</h3>
                    </div>
                    <div class="panel-body">
                        <input type="text" id="meeting-search-input" class="form-control" value="" placeholder="Search by name or description">
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading" id="new-meeting-panel-heading">
                        <h3 class="panel-title">New Meeting <span class="pull-right"><i class="fa fa-chevron-down" id="new-meeting-heading-chevron"></i></span></h3>
                    </div>
                    <div id="new-meeting-panel-body" class="panel-body hide">
                        <%= render 'form', meeting: @meeting %>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xs-12 col-sm-12 col-md-9 col-lg-9">
        <div id="meeting-list">
            <%= render 'meeting_list' %>
        </div>
    </div>
</div>

app/views/meetings/markdown.html.erb
<%=raw @markdown_rendered %>

app/views/meetings/new.html.erb
<h1>New Meeting</h1>

<%= render 'form', meeting: @meeting %>

<!--<%= link_to 'Back', meetings_path %>-->

app/views/meetings/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="row">
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <h1 class="panel-title"><%= @meeting.meeting_name %></h1>
      </div>
      <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <span class="pull-right">
          <a id="send-agenda-button" class="btn btn-default" target="_blank">Send Agenda</a>
          <a id="send-notes-button" class="btn btn-default" target="_blank">Send Notes</a>
          <a href="/meetings/<%= @meeting.id %>/md" class="btn btn-warning" target="_blank">Printable</a>
          <a href="/meetings/<%= @meeting.id %>/text" class="btn btn-success" target="_blank">Plain Text</a>
        </span>
      </div>
    </div>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <input type="hidden" id="meeting-id" value="<%= @meeting.id %>">
        
        <p>
          <%= @meeting.description %>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <div role="tabpanel">
          <!-- Nav tabs -->
          <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active">
              <a href="#goals" aria-controls="home" role="tab" data-toggle="tab">Goals</a>
            </li>
            <li role="presentation" id="attendee-tab">
              <a href="#attendees" aria-controls="home" role="tab" data-toggle="tab">Attendees</a>
            </li>
            <li role="presentation">
              <a href="#agenda" aria-controls="tab" role="tab" data-toggle="tab">Agenda</a>
            </li>
            <li role="presentation">
              <a href="#deliverables" aria-controls="tab" role="tab" data-toggle="tab">Deliverables</a>
            </li>
            <li role="presentation">
              <a href="#parking" aria-controls="home" role="tab" data-toggle="tab">Parking Lot</a>
            </li>
          </ul>
          <!-- Tab panes -->
          <div class="tab-content">
            
            <div role="tabpanel" class="tab-pane active" id="goals">
              <%= render "goal_tab" %>
            </div>
            <div role="tabpanel" class="tab-pane" id="attendees">
              <%= render 'attendee_tab' %>
            </div>
            <div role="tabpanel" class="tab-pane" id="agenda">
              <%= render 'agenda_tab' %>
            </div>
            <div role="tabpanel" class="tab-pane" id="deliverables">
              <%= render 'deliverables_tab' %>
            </div>
            <div role="tabpanel" class="tab-pane" id="parking">
              <%= render "parking_tab" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>


<div class="modal fade" id="agenda-mail-has-been-sent-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Agenda Sent</h4>
      </div>
      <div class="modal-body">
        The Goals and Agenda have been sent to the attendees.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="modal fade" id="notes-mail-has-been-sent-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Notes Sent</h4>
      </div>
      <div class="modal-body">
        Meeting notes have been sent to the attendees.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<%= render 'timeup_modal' %>
<!--
<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>
-->

app/views/meetings/text.html.erb
# <%= meeting.meeting_name %>
<%= meeting.description %>

##Attendees
<% meeting.attendees.each do |attendee| %>
* <%= attendee.email %>
<% end %>

## Goals
<% meeting.goals.each do |goal| %>
* <%= goal.goal_text %>
<% end %>

## Agenda
<% meeting.agenda_items.each do |agenda_item| %>
* <% if !agenda_item.done && !goals_and_agendas_only %>~~<% end %><%= agenda_item.agenda_item_text %><% if !agenda_item.done && !goals_and_agendas_only %>~~<% end %>
<% end %>

<% if !goals_and_agendas_only %>

## Deliverables
<% meeting.deliverables.each do |deliverable| %>
* <%= deliverable.attendee.email %>: <%= deliverable.deliverable_text %> by <%= deliverable.due_date %>

<% end %>

## Parking Lot
<% meeting.parking_lot_items.each do |parking_lot_item| %>
* <%= parking_lot_item.text %>
<% end %>

# Key
~~X~~ = Did not get to this item

<% end %>