config/routes.rb
Rails.application.routes.draw do

  get 'attendee/create'

  get 'attendee/delete'

  get '/companies/:id/attendees', to: 'companies#attendees'

  resources :companies
  get 'index/home'

  resources :comments
  resources :meetings
  resources :settings
  resources :users
  resources :goals
  resources :agenda_items
  resources :deliverables

  get '/agenda_items/:id/complete', to: 'agenda_items#complete'

  get '/meetings/:id/send_goals_and_agenda', to:"meetings#send_goals_and_agenda"

  get '/meetings/:id/send_notes', to:"meetings#send_notes"

  post '/parking_lot_items', to: 'parking_lot_items#create'

  delete '/parking_lot_items/:id', to: 'parking_lot_items#destroy'

  post '/attendees', to:'attendee#create'

  delete '/attendees/:id', to:'attendee#destroy'

  root 'meetings#index'
  
  get '/login', to: 'auth#login', as: 'auth_login_url'
  get '/logout', to: 'auth#logout', as: 'auth_logout_url'
  post '/login', to: 'auth#process_login'

  get '/meetings/:id/text', to: 'meetings#text'

  get '/meetings/:id/md', to: 'meetings#markdown'

  get '/meetings/:id/attendees', to: 'meetings#get_meeting_attendees'
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/agenda_item.rb
class AgendaItem < ApplicationRecord
  before_create :set_order
  belongs_to :meeting
  belongs_to :attendee

private
  def set_order
    max_order = AgendaItem.maximum(:order)
    
    self.order = 1
    
    if max_order
        self.order = max_order+1
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :meeting
  has_many :deliverables
  has_many :agenda_items
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :meeting
  belongs_to :user
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :meetings
    has_many :users
end

app/models/deliverable.rb
class Deliverable < ApplicationRecord
    belongs_to :attendee, :class_name => "Attendee"
    belongs_to :meeting
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :meeting
end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :meeting
  belongs_to :user
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  has_many :goals, :class_name => "Goal"
  has_many :agenda_items, :class_name => "AgendaItem"
  has_many :deliverables, :class_name => "Deliverable"
  has_many :parking_lot_items, :class_name => "ParkingLotItem"
  has_many :attendees, :class_name => "Attendee"


 def markdown_to_html(args)

      markdown_raw = ApplicationController.new.render_to_string('meetings/text', layout: false,locals: { meeting: self, goals_and_agendas_only: args[:goals_and_agendas_only]  })

      renderer = Redcarpet::Render::HTML.new(no_links: true, hard_wrap: true)

      markdown = Redcarpet::Markdown.new(renderer, extensions = {strikethrough: true})

      return markdown.render(markdown_raw)
  end
end

app/models/parking_lot_item.rb
class ParkingLotItem < ApplicationRecord
  belongs_to :meeting

end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    def full_name
        return self.first_name+" "+self.last_name
    end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def login
  end
  
  def process_login
    @user = User.find_by(email: params[:email]).try(:authenticate, params[:password])
    if(@user)
      session[:current_user] = @user.id
      session[:company_id] = @user.company_id
      redirect_to params[:redirect_to] || "/"
    else
     flash[:notice] = "There was a problem logging in. Please check your username and password and try again"
     redirect_to "/login?redirect_to="+params[:redirect_to]
    end
    
  end

  def logout
          session[:current_user] = nil
          session[:company_id] = nil
          redirect_to "/"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:meeting_id_id, :user_id_id, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendee_helper.rb
module AttendeeHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :meeting_id_id %>
    <%= f.text_field :meeting_id_id %>
  </div>

  <div class="field">
    <%= f.label :user_id_id %>
    <%= f.text_field :user_id_id %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_area :comment %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Meeting</th>
      <th>User</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.meeting_id %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.comment %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Meeting:</strong>
  <%= @comment.meeting_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @comment.comment %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>