config/routes.rb
Rails.application.routes.draw do

  get 'attendee/create'

  get 'attendee/delete'

  get '/companies/:id/attendees', to: 'companies#attendees'

  resources :companies
  get 'index/home'

  resources :comments
  resources :meetings
  resources :settings
  resources :users
  resources :goals
  resources :agenda_items
  resources :deliverables

  get '/agenda_items/:id/complete', to: 'agenda_items#complete'

  get '/meetings/:id/send_goals_and_agenda', to:"meetings#send_goals_and_agenda"

  get '/meetings/:id/send_notes', to:"meetings#send_notes"

  post '/parking_lot_items', to: 'parking_lot_items#create'

  delete '/parking_lot_items/:id', to: 'parking_lot_items#destroy'

  post '/attendees', to:'attendee#create'

  delete '/attendees/:id', to:'attendee#destroy'

  root 'meetings#index'
  
  get '/login', to: 'auth#login', as: 'auth_login_url'
  get '/logout', to: 'auth#logout', as: 'auth_logout_url'
  post '/login', to: 'auth#process_login'

  get '/meetings/:id/text', to: 'meetings#text'

  get '/meetings/:id/md', to: 'meetings#markdown'

  get '/meetings/:id/attendees', to: 'meetings#get_meeting_attendees'
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/agenda_item.rb
class AgendaItem < ApplicationRecord
  before_create :set_order
  belongs_to :meeting
  belongs_to :attendee

private
  def set_order
    max_order = AgendaItem.maximum(:order)
    
    self.order = 1
    
    if max_order
        self.order = max_order+1
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :meeting
  has_many :deliverables
  has_many :agenda_items
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :meeting
  belongs_to :user
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :meetings
    has_many :users
end

app/models/deliverable.rb
class Deliverable < ApplicationRecord
    belongs_to :attendee, :class_name => "Attendee"
    belongs_to :meeting
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :meeting
end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :meeting
  belongs_to :user
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  has_many :goals, :class_name => "Goal"
  has_many :agenda_items, :class_name => "AgendaItem"
  has_many :deliverables, :class_name => "Deliverable"
  has_many :parking_lot_items, :class_name => "ParkingLotItem"
  has_many :attendees, :class_name => "Attendee"


 def markdown_to_html(args)

      markdown_raw = ApplicationController.new.render_to_string('meetings/text', layout: false,locals: { meeting: self, goals_and_agendas_only: args[:goals_and_agendas_only]  })

      renderer = Redcarpet::Render::HTML.new(no_links: true, hard_wrap: true)

      markdown = Redcarpet::Markdown.new(renderer, extensions = {strikethrough: true})

      return markdown.render(markdown_raw)
  end
end

app/models/parking_lot_item.rb
class ParkingLotItem < ApplicationRecord
  belongs_to :meeting

end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    def full_name
        return self.first_name+" "+self.last_name
    end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def login
  end
  
  def process_login
    @user = User.find_by(email: params[:email]).try(:authenticate, params[:password])
    if(@user)
      session[:current_user] = @user.id
      session[:company_id] = @user.company_id
      redirect_to params[:redirect_to] || "/"
    else
     flash[:notice] = "There was a problem logging in. Please check your username and password and try again"
     redirect_to "/login?redirect_to="+params[:redirect_to]
    end
    
  end

  def logout
          session[:current_user] = nil
          session[:company_id] = nil
          redirect_to "/"
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_action :set_setting, only: [:show, :edit, :update, :destroy]

  # GET /settings
  # GET /settings.json
  def index
    @settings = Setting.all
  end

  # GET /settings/1
  # GET /settings/1.json
  def show
  end

  # GET /settings/new
  def new
    @setting = Setting.new
  end

  # GET /settings/1/edit
  def edit
  end

  # POST /settings
  # POST /settings.json
  def create
    @setting = Setting.new(setting_params)

    respond_to do |format|
      if @setting.save
        format.html { redirect_to @setting, notice: 'Setting was successfully created.' }
        format.json { render :show, status: :created, location: @setting }
      else
        format.html { render :new }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settings/1
  # PATCH/PUT /settings/1.json
  def update
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to @setting, notice: 'Setting was successfully updated.' }
        format.json { render :show, status: :ok, location: @setting }
      else
        format.html { render :edit }
        format.json { render json: @setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settings/1
  # DELETE /settings/1.json
  def destroy
    @setting.destroy
    respond_to do |format|
      format.html { redirect_to settings_url, notice: 'Setting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_setting
      @setting = Setting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def setting_params
      params.require(:setting).permit(:company_name, :average_salary, :number_of_employees)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendee_helper.rb
module AttendeeHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/settings/_form.html.erb
<%= form_for(setting) do |f| %>
  <% if setting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(setting.errors.count, "error") %> prohibited this setting from being saved:</h2>

      <ul>
      <% setting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :company_name %>
    <%= f.text_field :company_name %>
  </div>

  <div class="field">
    <%= f.label :average_salary %>
    <%= f.number_field :average_salary %>
  </div>

  <div class="field">
    <%= f.label :number_of_employees %>
    <%= f.number_field :number_of_employees %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/settings/edit.html.erb
<h1>Editing Setting</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Show', @setting %> |
<%= link_to 'Back', settings_path %>

app/views/settings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Settings</h1>

<table>
  <thead>
    <tr>
      <th>Company name</th>
      <th>Average salary</th>
      <th>Number of employees</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @settings.each do |setting| %>
      <tr>
        <td><%= setting.company_name %></td>
        <td><%= setting.average_salary %></td>
        <td><%= setting.number_of_employees %></td>
        <td><%= link_to 'Show', setting %></td>
        <td><%= link_to 'Edit', edit_setting_path(setting) %></td>
        <td><%= link_to 'Destroy', setting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Setting', new_setting_path %>

app/views/settings/new.html.erb
<h1>New Setting</h1>

<%= render 'form', setting: @setting %>

<%= link_to 'Back', settings_path %>

app/views/settings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Company name:</strong>
  <%= @setting.company_name %>
</p>

<p>
  <strong>Average salary:</strong>
  <%= @setting.average_salary %>
</p>

<p>
  <strong>Number of employees:</strong>
  <%= @setting.number_of_employees %>
</p>

<%= link_to 'Edit', edit_setting_path(@setting) %> |
<%= link_to 'Back', settings_path %>