config/routes.rb
Rails.application.routes.draw do

  get 'attendee/create'

  get 'attendee/delete'

  get '/companies/:id/attendees', to: 'companies#attendees'

  resources :companies
  get 'index/home'

  resources :comments
  resources :meetings
  resources :settings
  resources :users
  resources :goals
  resources :agenda_items
  resources :deliverables

  get '/agenda_items/:id/complete', to: 'agenda_items#complete'

  get '/meetings/:id/send_goals_and_agenda', to:"meetings#send_goals_and_agenda"

  get '/meetings/:id/send_notes', to:"meetings#send_notes"

  post '/parking_lot_items', to: 'parking_lot_items#create'

  delete '/parking_lot_items/:id', to: 'parking_lot_items#destroy'

  post '/attendees', to:'attendee#create'

  delete '/attendees/:id', to:'attendee#destroy'

  root 'meetings#index'
  
  get '/login', to: 'auth#login', as: 'auth_login_url'
  get '/logout', to: 'auth#logout', as: 'auth_logout_url'
  post '/login', to: 'auth#process_login'

  get '/meetings/:id/text', to: 'meetings#text'

  get '/meetings/:id/md', to: 'meetings#markdown'

  get '/meetings/:id/attendees', to: 'meetings#get_meeting_attendees'
    
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/agenda_item.rb
class AgendaItem < ApplicationRecord
  before_create :set_order
  belongs_to :meeting
  belongs_to :attendee

private
  def set_order
    max_order = AgendaItem.maximum(:order)
    
    self.order = 1
    
    if max_order
        self.order = max_order+1
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :meeting
  has_many :deliverables
  has_many :agenda_items
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :meeting
  belongs_to :user
end

app/models/company.rb
class Company < ApplicationRecord
    has_many :meetings
    has_many :users
end

app/models/deliverable.rb
class Deliverable < ApplicationRecord
    belongs_to :attendee, :class_name => "Attendee"
    belongs_to :meeting
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :meeting
end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :meeting
  belongs_to :user
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  has_many :goals, :class_name => "Goal"
  has_many :agenda_items, :class_name => "AgendaItem"
  has_many :deliverables, :class_name => "Deliverable"
  has_many :parking_lot_items, :class_name => "ParkingLotItem"
  has_many :attendees, :class_name => "Attendee"


 def markdown_to_html(args)

      markdown_raw = ApplicationController.new.render_to_string('meetings/text', layout: false,locals: { meeting: self, goals_and_agendas_only: args[:goals_and_agendas_only]  })

      renderer = Redcarpet::Render::HTML.new(no_links: true, hard_wrap: true)

      markdown = Redcarpet::Markdown.new(renderer, extensions = {strikethrough: true})

      return markdown.render(markdown_raw)
  end
end

app/models/parking_lot_item.rb
class ParkingLotItem < ApplicationRecord
  belongs_to :meeting

end

app/models/setting.rb
class Setting < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    def full_name
        return self.first_name+" "+self.last_name
    end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def login
  end
  
  def process_login
    @user = User.find_by(email: params[:email]).try(:authenticate, params[:password])
    if(@user)
      session[:current_user] = @user.id
      session[:company_id] = @user.company_id
      redirect_to params[:redirect_to] || "/"
    else
     flash[:notice] = "There was a problem logging in. Please check your username and password and try again"
     redirect_to "/login?redirect_to="+params[:redirect_to]
    end
    
  end

  def logout
          session[:current_user] = nil
          session[:company_id] = nil
          redirect_to "/"
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy, :attendees ]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end


  #Get all attendees of all meetings for this company for auto complete
  def attendees

    @company = Company.find(session[:company_id])

    attendee_array = Array.new()

    @company.meetings.each do |meeting|

      meeting.attendees.each do |attendee|
        
        unless attendee_array.include?(attendee.email)
          attendee_array << attendee.email
        end

      end

    end

    render json: attendee_array 
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_company
    @company = Company.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def company_params
    params.require(:company).permit(:name, :address, :address_ext, :city, :state, :zip)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendee_helper.rb
module AttendeeHelper
end

app/helpers/auth_helper.rb
module AuthHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/companies/_form.html.erb
<%= form_for(company) do |f| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :address_ext %>
    <%= f.text_field :address_ext %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="field">
    <%= f.label :zip %>
    <%= f.text_field :zip %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Address ext</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.address %></td>
        <td><%= company.address_ext %></td>
        <td><%= company.city %></td>
        <td><%= company.state %></td>
        <td><%= company.zip %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @company.address %>
</p>

<p>
  <strong>Address ext:</strong>
  <%= @company.address_ext %>
</p>

<p>
  <strong>City:</strong>
  <%= @company.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @company.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @company.zip %>
</p>

<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>